### ISSUE TITLE
Direct Response From callback

### ISSUE THREAD

**Issue by pinwhell** [JimTools/jwt-auth#7]
I am a bit concerned that i cant simply return a response from a before callback
why not checking for return if was a response type and if so return that given response directly
an alternative i tried was throwing exceptions but that didn't let me achieve my intended goal
![image](https://github.com/user-attachments/assets/09dcffb3-5434-4c8f-bb6d-fe93a47ad990)
directly returning a response from here?

**Comment by JimTools** [comment]
hi @pinwhell

If I understand correctly, you would like to modify the response before it gets passed to the next middleware?

The `before` callback is for modifying the request before it's passed to the next middleware. this is useful if you need to add more info to the request after the JWT has been decoded but before next middleware is called.

The `after` callback is for modifying the response after the next middleware has already been called, for example you want to include custom headers to the client, this is more or less the same as writing a custom middleware to modify the response.

Hope this helps.

**Comment by pinwhell** [comment]
> If I understand correctly, you would like to modify the response before it gets passed to the next middleware?

Not exactly, i want to create one right away(ex. for responding Unathorized), for example my use case i found it convenient to handle a given user endpoint access at the before of the JWT phase where i had immediate access to the freshly parsed JWT, i found it convenient to just deny from there, otherwise what happens is, i either need to write another middle-ware (that might be the way) or let the request hit the endpoint and somehow handle it there and modify the request in the way out (which already had consumed resources or reached somewhere should has to reach in the first place), notice that i am using before callback instead of a custom middle-ware for simplicity and convenience

> The `before` callback is for modifying the request before it's passed to the next middleware. this is useful if you need to add more info to the request after the JWT has been decoded but before next middleware is called.

i noticed this, that it was constrained this way, this is why i come here to suggest this

> The `after` callback is for modifying the response after the next middle-ware has already been called, for example you want to include custom headers to the client, this is more or less the same as writing a custom middle-ware to modify the response.

as mentioned before, this could work for that case because the response that comes to the after has already gone through the endpoint API and its its way out now ...

**Comment by JimTools** [comment]
Thanks for sharing this use case, this is a novel way of doing it which I've not considered.

I've inherited this project, so the reason for some of the decisions has been lost to time. I can see the pros and cons of doing it this way. 

My biggest dislike about this approach is that you are conflating authorization and authentication into one. I'd much rather have them separated into two clear concerns.  But... your project isn't my project and I won't tell you how to write that :P

I'll consider this in the v2 which I'm currently working on. 

**My Recommendation**
> I found it convenient to handle a given user endpoint access at the before of the JWT phase where I had immediate access to the freshly parsed JWT

This package only concerns itself with authentication. As long as the `attribute` option is set it will pass the decoded token in the request for ease of access. you could write a custom middleware to handle the authorization.

**Comment by pinwhell** [comment]
> I'd much rather have them separated into two clear concerns.

Agree, me too, it could be cool to keep concerns separated


> I'll consider this in the v2 which I'm currently working on.

Thanks so much for considering it, it might be dope convenient feature ...

> This package only concerns itself with authentication. As long as the `attribute` option is set it will pass the decoded token in the request for ease of access. you could write a custom middleware to handle the authorization.

i can overall see ... i guess thats the actual way to go to keep concerns separated, Thanks anyways, really apprecaited ...
