### ISSUE TITLE
v2: `psr/http-message` requirement difficult to satisfy

### ISSUE THREAD

**Issue by mbolli** [JimTools/jwt-auth#9]
Would it be possible to allow `psr/http-message` of `^1.0 || ^2.0` ?

My dependencies don't allow installing v2 currently:

```
guzzlehttp/psr7            2.7.0  requires psr/http-message (^1.1 || ^2.0) 
jimtools/jwt-auth          1.0.2  requires psr/http-message (^1.0|^2.0)    
middlewares/utils          v3.3.0 requires psr/http-message (^1.0)         
neomerx/cors-psr7          3.0.2  requires psr/http-message (^1.0)         
psr/http-factory           1.1.0  requires psr/http-message (^1.0 || ^2.0) 
psr/http-server-handler    1.0.2  requires psr/http-message (^1.0 || ^2.0) 
psr/http-server-middleware 1.0.2  requires psr/http-message (^1.0 || ^2.0) 
slim/csrf                  1.5.0  requires psr/http-message (^1.0 || ^2.0) 
slim/http                  1.4.0  requires psr/http-message (^1.1 || ^2.0) 
slim/psr7                  1.7.0  requires psr/http-message (^1.0 || ^2.0) 
slim/slim                  4.14.0 requires psr/http-message (^1.1 || ^2.0) 
slim/twig-view             3.4.1  requires psr/http-message (^1.1 || ^2.0) 
tuupola/cors-middleware    1.4.3  requires psr/http-message (^1.0.1)       
tuupola/slim-basic-auth    3.4.0  requires psr/http-message (^1.0.1|^2.0) 
```

**Comment by connectMyClub** [comment]
That would be really useful. I'm stuck upgrading from `tuupola/slim-jwt-auth 3.8.0` and would like to implement `google/apps-meet` but that requires `firebase/php-jwt > 6`

**Comment by JimTools** [comment]
@connectMyClub  I’ll look into over the weekend

**Comment by connectMyClub** [comment]
@JimTools Thank you very much. If I can get v1.0.2 working that would be a great. I'll then look at getting v2 up and running in the future but I think I'll run into other issues when I do.

Don't let it ruin your weekend though.

**Comment by connectMyClub** [comment]
I' updated to this 

`$app->add(new Tuupola\Middleware\JwtAuthentication([
    "secret" => ["acme" => "<My Secret>"],
    "algorithm" => ["acme" => "HS256"],
]));`

But my app isn't happy. I've not figured out why yet.

**Comment by connectMyClub** [comment]
This is the problem I'm seeing when trying to install v1.0.0

`  Problem 1
    - jimtools/jwt-auth 1.0.0 conflicts with tuupola/slim-jwt-auth 3.8.0.
    - jimtools/jwt-auth 1.0.0 conflicts with tuupola/slim-jwt-auth 3.7.0.
    - jimtools/jwt-auth 1.0.0 conflicts with tuupola/slim-jwt-auth 3.6.0.
    - jimtools/jwt-auth 1.0.0 conflicts with tuupola/slim-jwt-auth 3.5.2.
    - jimtools/jwt-auth 1.0.0 conflicts with tuupola/slim-jwt-auth 3.5.1.
    - jimtools/jwt-auth 1.0.0 conflicts with tuupola/slim-jwt-auth 3.5.0.
    - jimtools/jwt-auth 1.0.0 conflicts with tuupola/slim-jwt-auth 3.x-dev.
    - tuupola/slim-jwt-auth[3.0.0-rc.1, ..., 3.0.0-rc.4] require php ^5.5 || ^7.0 -> your php version (8.1.25) does not satisfy that requirement.
    - tuupola/slim-jwt-auth[3.0.0-rc.5, ..., 3.4.0] require php ^7.1 -> your php version (8.1.25) does not satisfy that requirement.
    - Root composer.json requires jimtools/jwt-auth 1.0.0 -> satisfiable by jimtools/jwt-auth[1.0.0].
    - Root composer.json requires tuupola/slim-jwt-auth ^3.0.0 -> satisfiable by tuupola/slim-jwt-auth[3.0.0-rc.1, ..., 3.x-dev].`

**Comment by connectMyClub** [comment]
v 1.0.1 installs OK

**Comment by connectMyClub** [comment]
I'll revisit this tomorrow

**Comment by connectMyClub** [comment]
@JimTools I've gone back to `"tuupola/slim-jwt-auth": "3.8.0"` and all works nicely. 

`$app->add(new Tuupola\Middleware\JwtAuthentication([
    "path" =>  ['/app'],
    "secret" => <My Secret>,
    "ignore" => [<Array>]
	]
));`

If I update to `"jimtools/jwt-auth": "1.0.1",` bearing in mind version 1.0.0 doesn't install because of conflicts. I use...

`$app->add(new Tuupola\Middleware\JwtAuthentication([
    "path" =>  ['/app'],
    "secret" => ['acme'=><My Secret>],
    "ignore" => [<Array>]
	]
));`

Looking at the update notes this should be all that is required. But I now get CORS errors.

`Access to fetch at <MY ENDPOINT> from origin <MY APP> has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Does this help at all?

**Comment by mbolli** [comment]
@connectMyClub actually my config for v1 is the same as for `tuupola/slim-jwt-auth`. no `acme` keys used.

**Comment by connectMyClub** [comment]
@mbolli Odd, that's not what it says here [https://github.com/JimTools/jwt-auth/tree/1.0.0](url)

I've just tried with the same config as I used with `tuupola/slim-jwt-auth` but that doesn't work either.

**Comment by JimTools** [comment]
@mbolli v2.2 has been released and allows for v1 of `psr/http-message`
